# Generated by Django 2.2.6 on 2023-01-07 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imovel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('plataforma_publicada', models.CharField(blank=True, db_column='plataforma_publicada', max_length=100, null=True)),
                ('taxa_plataforma', models.DecimalField(blank=True, db_column='taxa_plataforma', decimal_places=2, max_digits=12, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_column='data_criacao', null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True, db_column='data_atualizacao', null=True)),
                ('data_remocao', models.DateTimeField(blank=True, db_column='data_remocao', null=True)),
                ('id_imovel', models.ForeignKey(db_column='id_imovel', on_delete=django.db.models.deletion.PROTECT, related_name='anuncio', to='imovel.Imovel')),
            ],
            options={
                'db_table': 'anuncio',
            },
        ),
    ]
