"""
Django settings for challenge_geral project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from corsheaders.defaults import default_headers

# import sentry_sdk
# from sentry_sdk.integrations.django import DjangoIntegration

# sentry_sdk.init(
#     dsn="https://e3d347cf68bc494099e3840c1e32187e@o4504464867655680.ingest.sentry.io/4504464869425152",
#     integrations=[
#         DjangoIntegration(),
#     ]
# )

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

API_PATH = os.environ.get('API_PATH', 'api/challenge')

# CLIENT_ID e CLIENT_SECRET da API
# Criados no dash do django-admin
API_CLIENT_ID = os.environ.get('API_CLIENT_ID', 'tshJBHqLqKlNRPdAChzIDyyBKakT3i9BLB2C3VAq')
API_CLIENT_SECRET = os.environ.get('API_CLIENT_SECRET', 'cUoLqqKCURa40eUboM23r0QiluMRqmJtp91wiXfbLFiJQGmVNxthBRKdWJXVVKr11PHCpj7UlGNmtR0SueP7DZ4aVvAAUCUia010FONPY1zTJGz8qrnY6f3KKk98q1um')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'ke+7%$$6g$unb(pq-l=2xu*klb+8s0sg(*xw@17a_!&^gug_9k')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
	'django_filters',
	'oauth2_provider',
	'rest_framework',
	'rest_framework_tracking',
    'imovel',
    'anuncio',
    'reserva'
]

AUTHENTICATION_BACKENDS = (
	'oauth2_provider.backends.OAuth2Backend',
	# Uncomment following if you want to access the admin
	'django.contrib.auth.backends.ModelBackend',
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'corsheaders.middleware.CorsMiddleware',
	'oauth2_provider.middleware.OAuth2TokenMiddleware',
]

REST_FRAMEWORK = {
	# Use Django's standard `django.contrib.auth` permissions,
	# or allow read-only access for unauthenticated users.
	'DEFAULT_PERMISSION_CLASSES': (
		'rest_framework.permissions.IsAuthenticated',
	),

	'TEST_REQUEST_DEFAULT_FORMAT': 'json',

	'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],

	'DEFAULT_AUTHENTICATION_CLASSES': (
		'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
	),

	'DEFAULT_PAGINATION_CLASS': 'challenge_geral.pagination.CustomPagination',

	'DATETIME_FORMAT': '%d/%m/%Y %H:%M:%S',
	'DATE_FORMAT': '%d/%m/%Y',
	'TIME_FORMAT': '%H:%M:%S',

	'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'login': '1/second'
    }
}

OAUTH2_PROVIDER = {
	# this is the list of available scopes
	'SCOPES': {'read': 'Read scope', 'write': 'Write scope', 'groups': 'Access to your groups'},
	'ACCESS_TOKEN_EXPIRE_SECONDS': int(os.environ.get('ACCESS_TOKEN_EXPIRE_SECONDS', 86400)),
}

# Package django-cors-headers
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = list(default_headers) + [
    'content-disposition',
	'Content-Disposition',
]

# BACKGROUND_TASK_RUN_ASYNC = True

# host/IP local (descomentar para executar localmente)
ALLOWED_HOSTS = [
				'127.0.0.1',
				'localhost',
				'0.0.0.0',
				]

ROOT_URLCONF = 'challenge_geral.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'challenge_geral.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('MYSQL_DATABASE_NAME', 'challengeseazone'),
        'USER': os.environ.get('MYSQL_DATABASE_USER', 'root'),
        'PASSWORD': os.environ.get('MYSQL_DATABASE_PASSWORD', 'evangelho19'),
        'HOST':  os.environ.get('MYSQL_DATABASE_HOST', 'localhost'),
        'PORT': os.environ.get('MYSQL_DATABASE_PORT', '3306')
	}
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = False

USE_TZ = False

DATE_FORMAT = 'd/m/Y'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = '/media/'

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')