# Generated by Django 2.2.6 on 2023-01-07 17:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anuncio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('codigo_reserva', models.CharField(db_column='codigo_reserva', default=uuid.uuid4, max_length=100)),
                ('data_check_in', models.DateField(db_column='data_check_in')),
                ('data_check_out', models.DateField(db_column='data_check_out')),
                ('preco_total', models.DecimalField(blank=True, db_column='preco_total', decimal_places=2, max_digits=12, null=True)),
                ('comentario', models.CharField(blank=True, db_column='comentario', max_length=500, null=True)),
                ('quantidade_hospede', models.IntegerField(db_column='quantidade_hospede')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_column='data_criacao', null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True, db_column='data_atualizacao', null=True)),
                ('data_remocao', models.DateTimeField(blank=True, db_column='data_remocao', null=True)),
                ('id_anuncio', models.ForeignKey(db_column='id_anuncio', on_delete=django.db.models.deletion.PROTECT, related_name='reserva', to='anuncio.Anuncio')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
    ]
