# Generated by Django 2.2.6 on 2023-01-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('codigo_imovel', models.CharField(db_column='codigo_imovel', error_messages={'unique': 'O campo codigo_imovel é único e já existe no banco de dados.'}, max_length=100, unique=True)),
                ('limite_hospede', models.IntegerField(db_column='limite_hospede')),
                ('quantidade_banheiro', models.IntegerField(db_column='quantidade_banheiro')),
                ('aceita_pet', models.BooleanField(blank=True, db_column='aceita_pet', null=True)),
                ('valor_limpeza', models.DecimalField(blank=True, db_column='valor_limpeza', decimal_places=2, max_digits=12, null=True)),
                ('data_ativacao', models.DateField(blank=True, db_column='data_ativacao', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_column='data_criacao', null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True, db_column='data_atualizacao', null=True)),
                ('data_remocao', models.DateTimeField(blank=True, db_column='data_remocao', null=True)),
            ],
            options={
                'db_table': 'imovel',
            },
        ),
    ]
